### ISSUE TITLE
Slider icons < > not showing up properly

### ISSUE THREAD

**Issue by Ahmedkahin** [hasanmhallak/date_picker#9]
I want to use this package and slider icons are not showing up properly as you can see on the screenshot
![calendar](https://github.com/hasanmhallak/date_picker/assets/145427799/3e680d4a-2784-4c90-897d-97e42e85768b)

**Comment by hasanmhallak** [comment]
hey @Ahmedkahin Thank you for filing this issue.

it looks like you are missing `cupertino_icons` from your dependencies. I fix this issue in version `2.0.3` which i published rn.

feel free to use it or just simply add `cupertino_icons` to your `pubspec.yaml` file.

**Comment by jacobokoenig** [comment]
Hi @hasanmhallak. This is still an issue on version 4.2.0. I have cupertino_icons installed

<img width="265" height="242" alt="Image" src="https://github.com/user-attachments/assets/65e0ff91-7146-42ce-93cb-ea0746a26709" />

**Comment by hasanmhallak** [comment]
@jacobokoenig could you provide the pubspec file along with pubspec.lock file of the project that have the issue? I suspect that it uses an old version of this library because I removed `cupertino_icons` long time ago and used `Icons.arrow_forward_ios_rounded` &  `Icons.arrow_back_ios_rounded` which they come with Material lib.

Also could you try to use `Icons.arrow_forward_ios_rounded` &  `Icons.arrow_back_ios_rounded` in the project to see if they work fine?
